name: Publish to npm and GitHub

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Update version
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
          git fetch
          git checkout main
          npm version patch
      - name: Build and Test
        run: npm i && npm run build && npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish to npm
        run: npm run publish-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: push version bump back to repo
        run: git push origin main
