name: Publish to npm and GitHub

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Unit Testing
        run: npm i && npm run test

      - name: Update version
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
          git fetch
          git checkout main
          npm version patch
          npm -v
          git push origin main
      - run: npm run publish-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm run publish-gpr
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
